question_create:
    path: /questions/create
    methods: GET|POST
    controller: App\UserInterface\Controller\Question\CreateController

question_update:
    path: /questions/{id}/update
    methods: GET|POST
    controller: App\UserInterface\Controller\Question\UpdateController

registration:
    path: /registration
    methods: GET|POST
    controller: App\UserInterface\Controller\RegistrationController

login:
    path: /login
    methods: GET|POST
    controller: App\UserInterface\Controller\LoginController

logout:
    path: /logout
    methods: GET
    controller: App\UserInterface\Controller\LogoutController

home:
    path: /
    methods: GET
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: home.html.twig
